spring.application.name=seek-doc-query

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/seek_db
spring.datasource.username=postgres
spring.datasource.password=Postgres25
spring.jpa.hibernate.ddl-auto=update

# File upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# GEMINI (embeddings + chat via Spring AI)
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=text-embedding-004